version: 2.1
orbs:
  node: circleci/node@4.7

executors:
  node:
    docker:
      - image: cimg/node:16.15.0-browsers
    resource_class: small
    working_directory: ~/nextjs-blog-line
  ruby:
    docker:
      - image: cimg/ruby:3.1.2
    resource_class: small

commands:
  setup:
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          pkg-manager: yarn
      - run:
          name: Setup .vercel/project.json
          command: |
            mkdir -p .vercel
            touch .vercel/project.json
            echo '{"orgId":"'$VERCEL_ORG_ID'", "projectId":"'$VERCEL_PROJECT_ID'"}' >> .vercel/project.json
            cat .vercel/project.json

jobs:
  staging-deploy:
    executor: node
    steps:
      - setup
      - run:
          name: Staging Deploy
          command: yarn deploy:staging
  production-deploy:
    executor: node
    steps:
      - setup
      - run:
          name: Production Deploy
          command: yarn deploy:production
  pr-release:
    executor: ruby
    steps:
      - checkout
      - run: gem install -N git-pr-release
      - run: git-pr-release --no-fetch

workflows:
  version: 2
  deploy:
    jobs:
      - staging-deploy:
          filters:
            branches:
              only:
                - staging
      - pr-release:
          requires:
            - staging-deploy
          filters:
            branches:
              only:
                - staging
      - production-deploy:
          filters:
            branches:
              only:
                - main
