version: 2.1
orbs:
  node: circleci/node@4.7

executors:
  node:
    docker:
      - image: cimg/node:16.15.0
    resource_class: small
    working_directory: ~/nextjs-blog-line

jobs:
  deploy:
    executor: node
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: deploy
          command: yarn deploy

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main